<?php

function okta_sso_menu() {
  $items = [];

  $items['okta_sso'] = [
    'title'            => t('Okta SSO'),
    'page callback'    => 'okta_sso_login',
    'access arguments' => ['access content'],
    'description' => t('Okta SSO'),
    'type' => MENU_CALLBACK,
  ];

  $items['okta_sso_callback'] = [
    'title'            => t('Okta SSO OAuth Callback'),
    'page callback'    => 'okta_sso_oauth_callback',
    'access arguments' => ['access content'],
    'description' => t('Okta SSO OAuth Callback'),
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

function okta_sso_login() {
  $html = '';

  try {
    if (OktaSsoDrupal::isUserLoggedIn()) {
      $html = '<p>You are logged in</p>';
    }
    else {
      $oktaSsoSettings = new OktaSsoSettings();
      $oktaAuthenticator = OktaSsoFactory::getAuthenticator($oktaSsoSettings);
      $html = '<p><a href="' . $oktaAuthenticator->getLoginUrl() . '">Log in</a></p>';
    }
  }
  catch (Exception $e) {
    $html = $e->getMessage();
  }

  return $html;
}

function okta_sso_oauth_callback() {
  try {
    $code = okta_sso_oauth_getCode();
    okta_sso_oauth_assertMatchingState();

    $oktaSsoSettings = new OktaSsoSettings();
    $oktaSsoOauth = new OktaSsoOauth($oktaSsoSettings);
    $userName = $oktaSsoOauth->validate($code);

    $user = OktaSsoDrupal::loadUserByName($userName);
    OktaSsoDrupal::loginUser($user);

    return "<p>Hello $userName. You are logged in.</p>";
  }
  catch (Exception $e) {
    return '<p>' . $e->getMessage() . '</p>';
  }
}

function okta_sso_form_alter(&$form, &$form_state, $form_id) {
  try {
    if ($form_id == 'user_login' || $form_id == 'user_pass') {
      $oktaSsoSettings = new OktaSsoSettings();
      if ($oktaSsoSettings->disableLogin) {
        $form['#access'] = FALSE;
      }
    }
  }
  catch (Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
  }
}

function okta_sso_oauth_getCode() {
  if (!isset($_GET['code'])) {
    if (isset($_GET['error_description'])) {
      throw new Exception($_GET['error_description']);
    }
    else {
      throw new Exception('Missing code');
    }
  }

  return $_GET['code'];
}

function okta_sso_oauth_assertMatchingState() {
  if ($_SESSION['okta_sso_state'] != $_GET['state']) {
    throw new Exception('Bad state');
  }
}



